apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digitransit-ulm-dev
  namespace: default
spec:
  commonName: digitransit.ulm.dev
  duration: 2160h # 90d
  renewBefore: 672h # 28d
  dnsNames:
  - digitransit.ulm.dev
  - api.digitransit.ulm.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: tls-digitransitulmdev
